### ISSUE TITLE
Experiment: New DRL Parser : Test failure : Unknown language level

### ISSUE THREAD

**Issue by tkobayas** [apache/incubator-kie#5681]
**Parent issue:** https://github.com/apache/incubator-kie-drools/issues/5678

For example, `KnowledgeBuilderTest.testWarnOnFunctionReplacement`and some other tests fail with
```
java.lang.RuntimeException: Unknown language level
	at org.drools.drl.parser.DRLFactory.getDRLParser(DRLFactory.java:109)
	at org.drools.drl.parser.DRLFactory.buildParser(DRLFactory.java:71)
	at org.drools.drl.parser.DrlParser.parse(DrlParser.java:87)
	at org.drools.drl.parser.DrlParser.parse(DrlParser.java:93)
	at org.drools.compiler.builder.impl.KnowledgeBuilderImpl.addPackageFromDrl(KnowledgeBuilderImpl.java:314)
	at org.drools.compiler.builder.impl.KnowledgeBuilderImpl.addPackageFromDrl(KnowledgeBuilderImpl.java:300)
```

It means `DrlParser` and `DRLFactory` require more (hopefully clean) integration with the new parser.

**Comment by tkobayas** [comment]
I'm working in a way that removing `DRL10` and introduce a system property `drools.drl.antlr4.parser.enabled`.

Kind of overlapping https://github.com/apache/incubator-kie-drools/issues/5681

**Comment by tkobayas** [comment]
Fixed by https://github.com/apache/incubator-kie-drools/pull/5693
