### ISSUE TITLE
[new-parser] Some rules do not fire in MultiKieBaseTest

### ISSUE THREAD

**Issue by yurloc** [apache/incubator-kie#5709]
## Parent issue
- #5678 

## Failing tests
~~- `org.drools.model.codegen.execmodel.MultiKieBaseTest#testFoldersVsPackages`~~
~~- `org.drools.model.codegen.execmodel.MultiKieBaseTest#testHelloMultiKieBasesWithSharedDeclaredType`~~

 -> These 2 tests were already fixed probably by other fix (can't be sure which one). 

Instead, this test failed in MultiKieBaseTest
- `org.drools.model.codegen.execmodel.MultiKieBaseTest#testHelloWorldWithPackagesAnd2KieBases`

## Notes
- `STANDARD_FROM_DRL` only.

## Rule code snippet
- multiple rules

## Error output
```
13:41:52.267 [main] ERROR o.d.c.kie.util.ChangeSetBuilder.diffResource:187 - Error analyzing the contents of org/pkg2/r2.drl. Skipping.
java.lang.ArrayIndexOutOfBoundsException: arraycopy: source index -1 out of bounds for byte[141]
	at java.base/java.lang.System.arraycopy(Native Method)
	at java.base/java.util.Arrays.copyOfRangeByte(Arrays.java:3864)
	at java.base/java.util.Arrays.copyOfRange(Arrays.java:3854)
	at org.drools.compiler.kie.util.ChangeSetBuilder.diffDescrs(ChangeSetBuilder.java:247)
	at org.drools.compiler.kie.util.ChangeSetBuilder.diffResource(ChangeSetBuilder.java:172)
	at org.drools.compiler.kie.util.ChangeSetBuilder.build(ChangeSetBuilder.java:98)
	at org.drools.compiler.kie.builder.impl.InternalKieModule.getChanges(InternalKieModule.java:141)
	at org.drools.compiler.kie.builder.impl.KieContainerImpl.update(KieContainerImpl.java:246)
	at org.drools.compiler.kie.builder.impl.KieContainerImpl.update(KieContainerImpl.java:242)
	at org.drools.compiler.kie.builder.impl.KieContainerImpl.updateToVersion(KieContainerImpl.java:200)
	at org.drools.model.codegen.execmodel.MultiKieBaseTest.testHelloWorldWithPackagesAnd2KieBases(MultiKieBaseTest.java:105)
	...
### parse : ANTLR4_PARSER_ENABLED = true

org.opentest4j.AssertionFailedError: 
expected: 1
 but was: 2
Expected :1
Actual   :2
```

**Comment by tkobayas** [comment]
The root cause is that `RuleDescr.getStartCharacter()` returns `-1` (missed in `DRLVisitorImpl`), so the kbase is not updated (the error is logged).
https://github.com/apache/incubator-kie-drools/blob/dev-new-parser/drools-compiler/src/main/java/org/drools/compiler/kie/util/ChangeSetBuilder.java#L247

**Comment by tkobayas** [comment]
Fixed by https://github.com/apache/incubator-kie-drools/pull/5794
