### ISSUE TITLE
[new-parser] Broken QueryTest#testQueryWithInheritance: mismatched input 'init'

### ISSUE THREAD

**Issue by yurloc** [apache/incubator-kie#5713]
## Parent issue
- #5678 

## Failing tests
- `org.drools.model.codegen.execmodel.QueryTest#testQueryWithInheritance`

## Notes
- Both `STANDARD_FROM_DRL` and `PATTERN_DSL`.

## Rule code snippet
Complex rule with type declarations and a query. The problem is reported here:
```
rule init when
```

## Error output
```
### parse : ANTLR4_PARSER_ENABLED = true
line 13:5 mismatched input 'init' expecting {DRL_STRING_LITERAL, IDENTIFIER}
21:45:07.345 [main] ERROR o.d.c.k.b.impl.AbstractKieProject.buildKnowledgePackages:280 - Unable to build KieBaseModel:defaultKieBase
[13,5]: mismatched input 'init' expecting {DRL_STRING_LITERAL, IDENTIFIER}
[0,0]: Parser returned a null Package


java.lang.AssertionError: [Message [id=1, kieBase=defaultKieBase, level=ERROR, path=r0.drl, line=13, column=0
   text=mismatched input 'init' expecting {DRL_STRING_LITERAL, IDENTIFIER}], Message [id=2, kieBase=defaultKieBase, level=ERROR, path=r0.drl, line=0, column=0
   text=Parser returned a null Package]]

	at org.drools.model.codegen.execmodel.BaseModelTest.createKieBuilder(BaseModelTest.java:157)
	at org.drools.model.codegen.execmodel.BaseModelTest.createKieBuilder(BaseModelTest.java:132)
	at org.drools.model.codegen.execmodel.BaseModelTest.getKieContainer(BaseModelTest.java:121)
	at org.drools.model.codegen.execmodel.BaseModelTest.getKieContainer(BaseModelTest.java:114)
	at org.drools.model.codegen.execmodel.BaseModelTest.getKieSession(BaseModelTest.java:110)
	at org.drools.model.codegen.execmodel.BaseModelTest.getKieSession(BaseModelTest.java:106)
	at org.drools.model.codegen.execmodel.QueryTest.testQueryWithInheritance(QueryTest.java:1127)
```

**Comment by yurloc** [comment]
`/take`
