### ISSUE TITLE
[new-parser] Multiple broken tests in FromTest

### ISSUE THREAD

**Issue by yurloc** [apache/incubator-kie#5720]
## Parent issue
- #5678 

## Related issues
- https://github.com/apache/incubator-kie-drools/issues/5710
- https://github.com/apache/incubator-kie-drools/issues/5708

## Failing tests
- Many.

## Notes
- One test is special: `org.drools.model.codegen.execmodel.FromTest#testMultipleFromList` - this one fails in `STANDARD_FROM_DRL` only.

## Rule code snippet
```
 $selectedList: List() from accumulate(Measurement($m: this) from $lst, 
collectList(DummyService.mapEntry($m, $measurement.getListOfCodes())))
```

## Error output
```
### parse : ANTLR4_PARSER_ENABLED = true
21:45:12.485 [main] ERROR o.d.c.k.b.impl.AbstractKieProject.buildKnowledgePackages:280 - Unable to build KieBaseModel:defaultKieBase
Unable to Analyse Expression $m:
[Error: unable to resolve method using strict-mode: org.drools.model.codegen.execmodel.FromTest$Measurement.$m()]
[Near : {... $m ....}]
             ^ : [Rule name='will execute per each Measurement having ID color']

Rule Compilation error : [Rule name='will execute per each Measurement having ID color']
	$m cannot be resolved to a variable



java.lang.AssertionError: [Message [id=1, kieBase=defaultKieBase, level=ERROR, path=r0.drl, line=-1, column=0
   text=Unable to Analyse Expression $m:
[Error: unable to resolve method using strict-mode: org.drools.model.codegen.execmodel.FromTest$Measurement.$m()]
[Near : {... $m ....}]
             ^], Message [id=2, kieBase=defaultKieBase, level=ERROR, path=r0.drl, line=-1, column=0
   text=Rule Compilation error $m cannot be resolved to a variable]]

	at org.drools.model.codegen.execmodel.BaseModelTest.createKieBuilder(BaseModelTest.java:157)
	at org.drools.model.codegen.execmodel.BaseModelTest.createKieBuilder(BaseModelTest.java:132)
	at org.drools.model.codegen.execmodel.BaseModelTest.getKieContainer(BaseModelTest.java:121)
	at org.drools.model.codegen.execmodel.BaseModelTest.getKieContainer(BaseModelTest.java:114)
	at org.drools.model.codegen.execmodel.BaseModelTest.getKieSession(BaseModelTest.java:110)
	at org.drools.model.codegen.execmodel.BaseModelTest.getKieSession(BaseModelTest.java:106)
	at org.drools.model.codegen.execmodel.FromTest.testMultipleFromList(FromTest.java:1327)
```

**Comment by yurloc** [comment]
Fixed by multiple PRs.
