### ISSUE TITLE
[new-parser] Array initialization fails

### ISSUE THREAD

**Issue by yurloc** [apache/incubator-kie#5721]
## Parent issue
- #5678 

## Failing tests
- `org.drools.model.codegen.execmodel.ComplexRulesTest#test1`

## Notes
- `STANDARD_FROM_DRL` only.

## Rule code snippet
```
not ( 
        $policySet_not : ChildFactWithObject ( 
            id == $childFactWithObject.id , 
            eval(true == functions.arrayContainsInstanceWithParameters((Object[])$policySet_not.getObjectValue(), new Object[]{"getMessageId", "42103"}))
        )
    )
```

## Error output
```
### parse : ANTLR4_PARSER_ENABLED = true
line 1:97 extraneous input 'new' expecting {TIME_INTERVAL, DRL_STRING_LITERAL, '?/', DECIMAL_LITERAL, HEX_LITERAL, FLOAT_LITERAL, BOOL_LITERAL, STRING_LITERAL, 'null', '(', '[', '.', '<', '!', '~', '++', '--', '+', '-', '*', '/', IDENTIFIER}
line 1:109 no viable alternative at input 'Object[]{'
21:45:15.378 [main] ERROR o.d.c.k.b.impl.AbstractKieProject.buildKnowledgePackages:280 - Unable to build KieBaseModel:defaultKieBase
Unable to Analyse Expression true == functions.arrayContainsInstanceWithParameters((Object[])$policySet_not.getObjectValue(), new:
[Error: unbalanced braces ( ... )]
[Near : {... stanceWithParameters((Object[])$policySet_not.getO ....}]
                                                         ^ : [Rule name='R1']



java.lang.AssertionError: [Message [id=1, kieBase=defaultKieBase, level=ERROR, path=r0.drl, line=-1, column=0
   text=Unable to Analyse Expression true == functions.arrayContainsInstanceWithParameters((Object[])$policySet_not.getObjectValue(), new:
[Error: unbalanced braces ( ... )]
[Near : {... stanceWithParameters((Object[])$policySet_not.getO ....}]
                                                         ^]]

	at org.drools.model.codegen.execmodel.BaseModelTest.createKieBuilder(BaseModelTest.java:157)
	at org.drools.model.codegen.execmodel.BaseModelTest.createKieBuilder(BaseModelTest.java:132)
	at org.drools.model.codegen.execmodel.BaseModelTest.getKieContainer(BaseModelTest.java:121)
	at org.drools.model.codegen.execmodel.BaseModelTest.getKieContainer(BaseModelTest.java:114)
	at org.drools.model.codegen.execmodel.BaseModelTest.getKieSession(BaseModelTest.java:110)
	at org.drools.model.codegen.execmodel.BaseModelTest.getKieSession(BaseModelTest.java:106)
	at org.drools.model.codegen.execmodel.ComplexRulesTest.testComplexRule(ComplexRulesTest.java:158)
	at org.drools.model.codegen.execmodel.ComplexRulesTest.test1(ComplexRulesTest.java:103)
```

**Comment by yurloc** [comment]
`/take`
