### ISSUE TITLE
[new-parser] Unexpected global

### ISSUE THREAD

**Issue by yurloc** [apache/incubator-kie#5723]
## Parent issue
- #5678 

## Failing tests
- `org.drools.model.codegen.execmodel.GroupByTest#providedInstance`

## Notes
- Both `STANDARD_FROM_DRL` and `PATTERN_DSL`.

## Rule code snippet
```
import java.util.Map;
global Map results;
rule X when
```

## Error output
```
### parse : ANTLR4_PARSER_ENABLED = true

java.lang.RuntimeException: Unexpected global [results]

	at org.drools.kiesession.session.StatefulKnowledgeSessionImpl.setGlobal(StatefulKnowledgeSessionImpl.java:968)
	at org.drools.model.codegen.execmodel.GroupByTest.lambda$providedInstance$2(GroupByTest.java:88)
	at org.drools.model.codegen.execmodel.GroupByTest.lambda$assertSessionHasProperties$0(GroupByTest.java:63)
```

**Comment by yurloc** [comment]
`/take`
