### ISSUE TITLE
[new-parser] CEP rules: broken `after`, `before` and similar operators

### ISSUE THREAD

**Issue by yurloc** [apache/incubator-kie#5735]
## Parent issue
- #5678 

## Failing tests
- `org.drools.model.codegen.execmodel.CepTest#testAfterOnLongFields`

## Notes
- `STANDARD_FROM_DRL` only.

## Rule code snippet
```
    $b : StockTick( company == "ACME", timeFieldAsLong after[5,8] $a.timeFieldAsLong )
```

## Error output
```
### parse : ANTLR4_PARSER_ENABLED = true
14:50:01.117 [main] ERROR o.d.c.k.b.impl.AbstractKieProject.buildKnowledgePackages:280 - Unable to build KieBaseModel:kb
Predicate 'timeFieldAsLong' must be a Boolean expression
[Line: -1, Column: -1] : [Rule name='R']



java.lang.AssertionError: [Message [id=1, kieBase=kb, level=ERROR, path=r0.drl, line=-1, column=0
   text=Predicate 'timeFieldAsLong' must be a Boolean expression
[Line: -1, Column: -1]]]

	at org.drools.model.codegen.execmodel.BaseModelTest.createKieBuilder(BaseModelTest.java:157)
	at org.drools.model.codegen.execmodel.BaseModelTest.createKieBuilder(BaseModelTest.java:132)
	at org.drools.model.codegen.execmodel.BaseModelTest.getKieContainer(BaseModelTest.java:121)
	at org.drools.model.codegen.execmodel.BaseModelTest.getKieContainer(BaseModelTest.java:114)
	at org.drools.model.codegen.execmodel.BaseModelTest.getKieSession(BaseModelTest.java:110)
	at org.drools.model.codegen.execmodel.CepTest.testAfterOnLongFields(CepTest.java:616)
```

**Comment by yurloc** [comment]
`/take`
