### ISSUE TITLE
[new-parser] CEP rules: broken annotations

### ISSUE THREAD

**Issue by yurloc** [apache/incubator-kie#5736]
## Parent issue
- #5678 

## Failing tests
- `org.drools.model.codegen.execmodel.CepTest#testExpires`

## Notes
- Both `STANDARD_FROM_DRL` and `PATTERN_DSL`.

## Rule code snippet
```
declare StockFact
    @role( value = event )
    @expires( value = 2s, policy = TIME_SOFT )
end
```

## Error output
```
### parse : ANTLR4_PARSER_ENABLED = true
line 6:22 no viable alternative at input 'value = 2s'
line 6:20 mismatched input '=' expecting ':'
line 6:45 extraneous input ')' expecting 'end'
14:50:01.178 [main] ERROR o.d.c.k.b.impl.AbstractKieProject.buildKnowledgePackages:280 - Unable to build KieBaseModel:kb
[6,22]: no viable alternative at input 'value = 2s'
[6,20]: mismatched input '=' expecting ':'
[6,45]: extraneous input ')' expecting 'end'
[0,0]: Parser returned a null Package


java.lang.AssertionError: [Message [id=1, kieBase=kb, level=ERROR, path=r0.drl, line=6, column=0
   text=no viable alternative at input 'value = 2s'], Message [id=2, kieBase=kb, level=ERROR, path=r0.drl, line=6, column=0
   text=mismatched input '=' expecting ':'], Message [id=3, kieBase=kb, level=ERROR, path=r0.drl, line=6, column=0
   text=extraneous input ')' expecting 'end'], Message [id=4, kieBase=kb, level=ERROR, path=r0.drl, line=0, column=0
   text=Parser returned a null Package]]

	at org.drools.model.codegen.execmodel.BaseModelTest.createKieBuilder(BaseModelTest.java:157)
	at org.drools.model.codegen.execmodel.BaseModelTest.createKieBuilder(BaseModelTest.java:132)
	at org.drools.model.codegen.execmodel.BaseModelTest.getKieContainer(BaseModelTest.java:121)
	at org.drools.model.codegen.execmodel.BaseModelTest.getKieContainer(BaseModelTest.java:114)
	at org.drools.model.codegen.execmodel.BaseModelTest.getKieSession(BaseModelTest.java:110)
	at org.drools.model.codegen.execmodel.CepTest.testExpires(CepTest.java:452)
```

**Comment by yurloc** [comment]
`/take`
