### ISSUE TITLE
[new-parser] Broken cron and interval timer attributes

### ISSUE THREAD

**Issue by yurloc** [apache/incubator-kie#5738]
## Parent issue
- #5678 

## Failing tests
- `org.drools.model.codegen.execmodel.CepTest#testCalendarsWithCronAndStartAndEnd`
- `org.drools.model.codegen.execmodel.CepTest#testIntervalTimer`

## Notes
- `PATTERN_DSL` only.

## Rule code snippet
```
rule xxx
  timer (cron: 0 0 0 * * ?) 
```

## Error output
```
### parse : ANTLR4_PARSER_ENABLED = true
14:50:02.849 [main] ERROR o.d.c.k.b.impl.AbstractKieProject.buildKnowledgePackages:280 - Unable to build KieBaseModel:kb
InvalidExpressionErrorResult: (cron: 0 0 0 * * ?)


java.lang.AssertionError: [Message [id=1, kieBase=kb, level=ERROR, path=r0.drl, line=-1, column=0
   text=(cron: 0 0 0 * * ?)]]

	at org.drools.model.codegen.execmodel.BaseModelTest.createKieBuilder(BaseModelTest.java:157)
	at org.drools.model.codegen.execmodel.BaseModelTest.createKieBuilder(BaseModelTest.java:132)
	at org.drools.model.codegen.execmodel.BaseModelTest.getKieContainer(BaseModelTest.java:121)
	at org.drools.model.codegen.execmodel.BaseModelTest.getKieContainer(BaseModelTest.java:114)
	at org.drools.model.codegen.execmodel.BaseModelTest.getKieSession(BaseModelTest.java:110)
	at org.drools.model.codegen.execmodel.CepTest.testCalendarsWithCronAndStartAndEnd(CepTest.java:1223)
```

**Comment by yurloc** [comment]
`/take`
