### ISSUE TITLE
[new-parser] Broken half-binary expressions

### ISSUE THREAD

**Issue by yurloc** [apache/incubator-kie#5739]
## Parent issue
- #5678 

## Failing tests
- `org.drools.model.codegen.execmodel.HalfBinaryTest#testHalfBinaryOnComparable`

## Notes
- Both `STANDARD_FROM_DRL` and `PATTERN_DSL`.

## Rule code snippet
```
    String(this (> "C" && < "K"))
```

## Error output
```
### parse : ANTLR4_PARSER_ENABLED = true
line 2:17 no viable alternative at input 'this (>'
14:50:10.342 [main] ERROR o.d.c.k.b.impl.AbstractKieProject.buildKnowledgePackages:280 - Unable to build KieBaseModel:defaultKieBase
[2,17]: no viable alternative at input 'this (>'
[0,0]: Parser returned a null Package


java.lang.AssertionError: [Message [id=1, kieBase=defaultKieBase, level=ERROR, path=r0.drl, line=2, column=0
   text=no viable alternative at input 'this (>'], Message [id=2, kieBase=defaultKieBase, level=ERROR, path=r0.drl, line=0, column=0
   text=Parser returned a null Package]]

	at org.drools.model.codegen.execmodel.BaseModelTest.createKieBuilder(BaseModelTest.java:157)
	at org.drools.model.codegen.execmodel.BaseModelTest.createKieBuilder(BaseModelTest.java:132)
	at org.drools.model.codegen.execmodel.BaseModelTest.getKieContainer(BaseModelTest.java:121)
	at org.drools.model.codegen.execmodel.BaseModelTest.getKieContainer(BaseModelTest.java:114)
	at org.drools.model.codegen.execmodel.BaseModelTest.getKieSession(BaseModelTest.java:110)
	at org.drools.model.codegen.execmodel.BaseModelTest.getKieSession(BaseModelTest.java:106)
	at org.drools.model.codegen.execmodel.HalfBinaryTest.testHalfBinaryOnComparable(HalfBinaryTest.java:113)
```

**Comment by tkobayas** [comment]
Fixed by https://github.com/apache/incubator-kie-drools/pull/5845
