### ISSUE TITLE
[new-parser] `Missing left node` with `instanceof`

### ISSUE THREAD

**Issue by tkobayas** [apache/incubator-kie#5773]
## Parent issue
- #5678 

## Failing tests
After applying https://github.com/apache/incubator-kie-drools/pull/5771 , 
- `org.drools.model.codegen.execmodel.NullSafeDereferencingTest.testNullSafeDereferncingWithInstanceof`

## Notes
- `STANDARD_FROM_DRL` only.

## Rule code snippet
```
    $p : Person( !(this instanceof MysteriousMan), address!.city != null )
```

## Error output
```
[ERROR] org.drools.model.codegen.execmodel.NullSafeDereferencingTest.testNullSafeDereferncingWithInstanceof[STANDARD_FROM_DRL] -- Time elapsed: 0.063 s <<< FAILURE!
java.lang.AssertionError: 
[Message [id=1, kieBase=defaultKieBase, level=ERROR, path=r0.drl, line=-1, column=0
   text=Unable to Analyse Expression  instanceof MysteriousMan:
[Error: Missing left node]
[Near : {... instanceof MysteriousMan ....}]
                        ^]]
	at org.drools.model.codegen.execmodel.BaseModelTest.createKieBuilder(BaseModelTest.java:157)
	at org.drools.model.codegen.execmodel.BaseModelTest.createKieBuilder(BaseModelTest.java:132)
	at org.drools.model.codegen.execmodel.BaseModelTest.getKieContainer(BaseModelTest.java:121)
	at org.drools.model.codegen.execmodel.BaseModelTest.getKieContainer(BaseModelTest.java:114)
	at org.drools.model.codegen.execmodel.BaseModelTest.getKieSession(BaseModelTest.java:110)
	at org.drools.model.codegen.execmodel.BaseModelTest.getKieSession(BaseModelTest.java:106)
	at org.drools.model.codegen.execmodel.NullSafeDereferencingTest.testNullSafeDereferncingWithInstanceof(NullSafeDereferencingTest.java:417)
```

**Comment by tkobayas** [comment]
This is already fixed probably thanks to https://github.com/apache/incubator-kie-drools/pull/5845
