### ISSUE TITLE
[new-parser] Elementary trait support is missing

### ISSUE THREAD

**Issue by yurloc** [apache/incubator-kie#5816]
## Parent issue
- #5678 

## Failing tests
- `org.drools.traits.compiler.factmodel.traits.LegacyTraitTest#traitWithPojoInterface`

## Notes
- Blocks all tests under `drools-traits`.

## Rule code snippet
```
declare trait ExtendedProcedure
   @role( event )
end
```

## Error output
```
### parse : ANTLR4_PARSER_ENABLED = true
line 6:35 mismatched input '@' expecting ':'
line 6:40 mismatched input '(' expecting {'end', '[', ';', '.', '=', '<', '@', IDENTIFIER}
line 6:75 mismatched input 'extends' expecting ':'

java.lang.RuntimeException: [6,35]: mismatched input '@' expecting ':'
[6,40]: mismatched input '(' expecting {'end', '[', ';', '.', '=', '<', '@', IDENTIFIER}
[6,75]: mismatched input 'extends' expecting ':'
[0,0]: Parser returned a null Package


	at org.drools.traits.compiler.factmodel.traits.LegacyTraitTest.getSessionFromString(LegacyTraitTest.java:80)
	at org.drools.traits.compiler.factmodel.traits.LegacyTraitTest.traitWithPojoInterface(LegacyTraitTest.java:205)
```

**Comment by yurloc** [comment]
`/take`
