### ISSUE TITLE
[new-parser] Class literal not supported by expression parser

### ISSUE THREAD

**Issue by yurloc** [apache/incubator-kie#5833]
## Parent issue
- #5678 

## Failing tests
- `org.drools.traits.compiler.factmodel.traits.TraitTest#testIsAEvaluatorOnClassification`

## Rule code snippet
```
$t : org.drools.base.factmodel.traits.Thing( $c : core, this not isA t.x.E.class, this isA t.x.D.class )
```

## Error output
```
20:22:51.158 [main] WARN  o.d.c.k.builder.impl.KieBuilderImpl.packageNameForFile:396 - File 'file0.drl' is in folder '' but declares package 't.x'. It is advised to have a correspondance between package and folder names.
### parse : ANTLR4_PARSER_ENABLED = true
line 1:19 no viable alternative at input '.class'
20:22:51.189 [main] ERROR o.d.c.k.b.impl.AbstractKieProject.buildKnowledgePackages:280 - Unable to build KieBaseModel:defaultKieBase
Unable to parse pattern expression:
[ERR 101] Line 1:19 no viable alternative at input '.class' : [Rule name='Rule 0 >> http://t/x#D']



java.lang.RuntimeException: [Message [id=1, kieBase=defaultKieBase, level=ERROR, path=file0.drl, line=27, column=0
   text=Unable to parse pattern expression:
[ERR 101] Line 1:19 no viable alternative at input '.class']]

	at org.kie.internal.utils.KieHelper.getKieContainer(KieHelper.java:127)
	at org.kie.internal.utils.KieHelper.build(KieHelper.java:89)
	at org.kie.internal.utils.KieHelper.build(KieHelper.java:84)
	at org.drools.traits.compiler.factmodel.traits.TraitTest.getSessionFromString(TraitTest.java:145)
	at org.drools.traits.compiler.factmodel.traits.TraitTest.testIsAEvaluatorOnClassification(TraitTest.java:2699)
```

**Comment by yurloc** [comment]
`/take`
