### ISSUE TITLE
Flaky KieContainerTest.testIncrementalCompilationSynchronization timeout

### ISSUE THREAD

**Issue by tkobayas** [apache/incubator-kie#5847]
KieContainerTest.testIncrementalCompilationSynchronization very rarely hits 20 sec timeout.
```
[2022-03-03T16:20:06.546Z] [ERROR] Tests run: 10, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 20.29 s <<< FAILURE! - in org.drools.mvel.integrationtests.KieContainerTest
[2022-03-03T16:20:06.546Z] [ERROR] testIncrementalCompilationSynchronization[KieBase type=CLOUD_IDENTITY](org.drools.mvel.integrationtests.KieContainerTest)  Time elapsed: 20.022 s  <<< ERROR!
[2022-03-03T16:20:06.546Z] org.junit.runners.model.TestTimedOutException: test timed out after 20000 milliseconds
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.phreak.AddRemoveRule.findPathToFlush(AddRemoveRule.java:647)
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.reteoo.LeftInputAdapterNode.doInsertSegmentMemory(LeftInputAdapterNode.java:255)
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.reteoo.LeftInputAdapterNode.doInsertObject(LeftInputAdapterNode.java:232)
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.reteoo.LeftInputAdapterNode.assertObject(LeftInputAdapterNode.java:176)
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.reteoo.SingleObjectSinkAdapter.propagateAssertObject(SingleObjectSinkAdapter.java:70)
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.reteoo.ObjectTypeNode.propagateAssert(ObjectTypeNode.java:297)
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.reteoo.ObjectTypeNode.assertInitialFact(ObjectTypeNode.java:265)
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.impl.StatefulKnowledgeSessionImpl.initInitialFact(StatefulKnowledgeSessionImpl.java:756)
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.impl.StatefulKnowledgeSessionImpl.initInitialFact(StatefulKnowledgeSessionImpl.java:744)
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.impl.StatefulKnowledgeSessionImpl.bindRuleBase(StatefulKnowledgeSessionImpl.java:406)
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.impl.StatefulKnowledgeSessionImpl.<init>(StatefulKnowledgeSessionImpl.java:332)
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.impl.StatefulKnowledgeSessionImpl.<init>(StatefulKnowledgeSessionImpl.java:278)
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.common.PhreakWorkingMemoryFactory.createWorkingMemory(PhreakWorkingMemoryFactory.java:35)
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.impl.KnowledgeBaseImpl.internalCreateStatefulKnowledgeSession(KnowledgeBaseImpl.java:381)
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.impl.KnowledgeBaseImpl.newKieSession(KnowledgeBaseImpl.java:365)
[2022-03-03T16:20:06.547Z]      at app//org.drools.core.impl.KnowledgeBaseImpl.newKieSession(KnowledgeBaseImpl.java:344)
[2022-03-03T16:20:06.547Z]      at app//org.drools.compiler.kie.builder.impl.KieContainerImpl.newKieSession(KieContainerImpl.java:599)
[2022-03-03T16:20:06.547Z]      at app//org.drools.compiler.kie.builder.impl.KieContainerImpl.newKieSession(KieContainerImpl.java:519)
[2022-03-03T16:20:06.547Z]      at app//org.drools.compiler.kie.builder.impl.KieContainerImpl.newKieSession(KieContainerImpl.java:502)
[2022-03-03T16:20:06.547Z]      at app//org.drools.mvel.integrationtests.KieContainerTest.testIncrementalCompilationSynchronization(KieContainerTest.java:279)
[2022-03-03T16:20:06.547Z]      at java.base@11.0.14.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-03-03T16:20:06.547Z]      at java.base@11.0.14.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-03-03T16:20:06.547Z]      at java.base@11.0.14.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-03-03T16:20:06.547Z]      at java.base@11.0.14.1/java.lang.reflect.Method.invoke(Method.java:566)
[2022-03-03T16:20:06.547Z]      at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
[2022-03-03T16:20:06.547Z]      at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[2022-03-03T16:20:06.547Z]      at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
[2022-03-03T16:20:06.547Z]      at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[2022-03-03T16:20:06.547Z]      at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
[2022-03-03T16:20:06.547Z]      at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
[2022-03-03T16:20:06.547Z]      at java.base@11.0.14.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2022-03-03T16:20:06.547Z]      at java.base@11.0.14.1/java.lang.Thread.run(Thread.java:829)

```

**Comment by tkobayas** [comment]
I see it both in linux and windows, window is relatively frequent.
