### ISSUE TITLE
[new-parser] FromAccumulate/result does not preserve whitespace

### ISSUE THREAD

**Issue by yurloc** [apache/incubator-kie#5885]
## Parent issue
- #5678 

## Failing tests
- `org.drools.testcoverage.regression.AccumulateRecalculationTest#testAccumulateWithNoLoop`

## Rule code snippet
```
    result ( new Integer(total) )
```

## Error output
```
09:53:25,996 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback-test.xml] at [file:/var/home/jlocker/src/github.com/kiegroup/drools/drools-test-coverage/test-suite/target/test-classes/logback-test.xml]
09:53:25,997 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback-test.xml] occurs multiple times on the classpath.
09:53:25,997 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback-test.xml] occurs at [file:/var/home/jlocker/src/github.com/kiegroup/drools/drools-test-coverage/test-suite/target/test-classes/logback-test.xml]
09:53:25,997 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback-test.xml] occurs at [file:/var/home/jlocker/src/github.com/kiegroup/drools/drools-base/target/test-classes/logback-test.xml]
09:53:25,997 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback-test.xml] occurs at [file:/var/home/jlocker/src/github.com/kiegroup/drools/drools-core/target/test-classes/logback-test.xml]
09:53:25,997 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback-test.xml] occurs at [file:/var/home/jlocker/src/github.com/kiegroup/drools/drools-legacy-test-util/target/test-classes/logback-test.xml]
09:53:26,094 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
09:53:26,095 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
09:53:26,111 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [consoleAppender]
09:53:26,120 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
09:53:26,216 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.kie] to WARN
09:53:26,216 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.drools] to WARN
09:53:26,216 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.drools.compiler.kie.builder.impl] to ERROR
09:53:26,216 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to WARN
09:53:26,216 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [consoleAppender] to Logger[ROOT]
09:53:26,218 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
09:53:26,220 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@1e67a849 - Registering current configuration as safe fallback point

09:53:26.275 [main] WARN  o.k.m.i.embedder.MavenSettings.initSettings:107 - Environment variable M2_HOME is not set
### parse : ANTLR4_PARSER_ENABLED = true
09:53:29.676 [main] ERROR o.d.c.k.b.impl.AbstractKieProject.buildKnowledgePackages:280 - Unable to build KieBaseModel:defaultKieBase
Rule Compilation error : [Rule name='RuleAccumulate']
	The method newInteger(int) is undefined for the type Rule_RuleAccumulate1986305453.Accumulate0



java.lang.RuntimeException: [Message [id=1, kieBase=defaultKieBase, level=ERROR, path=file0.drl, line=2, column=0
   text=Rule Compilation error The method newInteger(int) is undefined for the type Rule_RuleAccumulate1986305453.Accumulate0]]

	at org.kie.internal.utils.KieHelper.getKieContainer(KieHelper.java:127)
	at org.kie.internal.utils.KieHelper.build(KieHelper.java:89)
	at org.kie.internal.utils.KieHelper.build(KieHelper.java:84)
	at org.drools.testcoverage.regression.AccumulateRecalculationTest.scenario(AccumulateRecalculationTest.java:161)
	at org.drools.testcoverage.regression.AccumulateRecalculationTest.testAccumulateWithNoLoop(AccumulateRecalculationTest.java:69)
```

**Comment by yurloc** [comment]
`/take`
