### ISSUE TITLE
Some tests failing in incremental compilation

### ISSUE THREAD

**Issue by pibizza** [apache/incubator-kie#6190]
Some tests are failing - apparently because of a memory issue.

The failures were not discovered before  because they were tests executed only on demand - so called TurtleTests.

AddRemoveGenerated2RulesEvalTest.java
AddRemoveGenerated2RulesIntegerTest.java
AddRemoveGenerated2RulesMapContainsTest.java
AddRemoveGenerated2RulesNotNotTest.java
AddRemoveGenerated2RulesNotTest.java
AddRemoveGenerated2RulesStringIntegerTest.java
AddRemoveGenerated2RulesStringTest.java

The test 

IncrementalCompilationTest.testDecisionTable

fails only after the migration to Junit5.

**Comment by pibizza** [comment]
An easy way to reproduce it:
in the first test execute:
testInsertFactsFireRulesRemoveRulesReinsertRulesRevertedRules

This get stuck after 27 or so combinations.

**Comment by mariofusco** [comment]
Fixed by https://github.com/apache/incubator-kie-drools/commit/14f5601b464965e50141fef98ba67a16de6886c5

**Comment by pibizza** [comment]
Unfortunately there are still some tests failing. AddRemoveRulesAddDeleteFactsTest is failing with a null pointer exception. 

This is the trace

java.lang.NullPointerException: Cannot invoke "org.drools.core.reteoo.SegmentMemory.getTipNode()" because "smem" is null
	at org.drools.core.reteoo.LeftInputAdapterNode.retractLeftTuple(LeftInputAdapterNode.java:378)
	at org.drools.core.reteoo.ObjectTypeNode.lambda$retractLeftTuples$0(ObjectTypeNode.java:273)
	at org.drools.core.common.DefaultFactHandle$SingleLinkedTuples.forEachLeftTuple(DefaultFactHandle.java:616)
	at org.drools.core.common.DefaultFactHandle.forEachLeftTuple(DefaultFactHandle.java:980)
	at org.drools.core.reteoo.ObjectTypeNode.retractLeftTuples(ObjectTypeNode.java:272)
	at org.drools.core.reteoo.ObjectTypeNode.doRetractObject(ObjectTypeNode.java:250)
	at org.drools.core.reteoo.ObjectTypeNode.retractObject(ObjectTypeNode.java:233)
	at org.drools.core.reteoo.EntryPointNode.propagateRetract(EntryPointNode.java:322)
	at org.drools.core.phreak.PropagationEntry$Delete.execute(PropagationEntry.java:430)
	at org.drools.core.phreak.PropagationEntry$Delete.internalExecute(PropagationEntry.java:426)
	at org.drools.core.phreak.PropagationEntry.execute(PropagationEntry.java:56)
	at org.drools.core.phreak.SynchronizedPropagationList.flush(SynchronizedPropagationList.java:105)
	at org.drools.core.phreak.SynchronizedPropagationList.flush(SynchronizedPropagationList.java:100)
	at org.drools.kiesession.agenda.DefaultAgenda.fireLoop(DefaultAgenda.java:610)
	at org.drools.kiesession.agenda.DefaultAgenda.internalFireAllRules(DefaultAgenda.java:573)
	at org.drools.kiesession.agenda.DefaultAgenda.fireAllRules(DefaultAgenda.java:565)
	at org.drools.kiesession.session.StatefulKnowledgeSessionImpl.internalFireAllRules(StatefulKnowledgeSessionImpl.java:1093)
	at org.drools.kiesession.session.StatefulKnowledgeSessionImpl.fireAllRules(StatefulKnowledgeSessionImpl.java:1084)
	at org.drools.kiesession.session.StatefulKnowledgeSessionImpl.fireAllRules(StatefulKnowledgeSessionImpl.java:1068)
	at org.drools.compiler.integrationtests.incrementalcompilation.AddRemoveRulesAddDeleteFactsTest.testAddRemoveRulesAddRemoveFacts(AddRemoveRulesAddDeleteFactsTest.java:71)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

**Comment by mariofusco** [comment]
> Unfortunately there are still some tests failing. AddRemoveRulesAddDeleteFactsTest is failing with a null pointer exception.

This pull request https://github.com/apache/incubator-kie-drools/pull/6210 should also solve this problem.

**Comment by pibizza** [comment]
Thanks!

**Comment by mariofusco** [comment]
Fix merged.
