### ISSUE TITLE
Workflow - Parallel execution of multiple timers leads to stale process instances

### ISSUE THREAD

**Issue by gitgabrio** [apache/incubator-kie#7038]
Parallel execution of user tasks, under heavy load, may lead to not-consistent final status.

The issue could be recreated with the [compact-architecture-example](https://github.com/apache/incubator-kie-tools/tree/eee1b797d9e4eaf681245cbcd512b6736b9365e8/examples/jbpm-compact-architecture-example), sending big amount of "hiring" requests (e.g. 10000) over a short period of time.

Currently, in "random" way, there is the following error shown:

```
2024-11-22 12:24:37 WARN  [io.vertx.core.impl.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2134 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
	at java.base@17.0.11/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@17.0.11/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
	at java.base@17.0.11/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
	at java.base@17.0.11/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3465)
	at java.base@17.0.11/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3436)
	at java.base@17.0.11/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
	at java.base@17.0.11/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2072)
	at org.kie.kogito.jobs.embedded.JobInVMEventPublisher.publishJobStatusChange(JobInVMEventPublisher.java:84)
	at org.kie.kogito.jobs.embedded.JobInVMEventPublisher_ClientProxy.publishJobStatusChange(Unknown Source)
	at org.kie.kogito.jobs.service.repository.impl.BaseReactiveJobRepository$$Lambda$1554/0x00002aab2ab90248.apply(Unknown Source)
	at java.base@17.0.11/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base@17.0.11/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base@17.0.11/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at io.vertx.core.Future.lambda$toCompletionStage$3(Future.java:581)
	at io.vertx.core.Future$$Lambda$767/0x00002aab2a7d9410.handle(Unknown Source)
	at io.vertx.core.impl.future.FutureImpl$4.onSuccess(FutureImpl.java:176)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureBase$$Lambda$922/0x00002aab2a87fbb8.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@17.0.11/java.lang.Thread.run(Thread.java:840)
```

and the following query shows some entry:

```sql
select * from processes where start_time is null or variables is null; 
```

The expectations are

```sql
select * from processes where start_time is null or variables is null; /*-> there should be no record*/
select * from process_instance_error_log; /*-> there should be no record*/
select * from process_instances; /*-> there should be no record*/
select * from processes; /*-> there should be all the processes fired*/
```

**Comment by pefernan** [comment]
Reopening the issue since the change got rolled back due to an unexpected side effect when using the job service addon in conjunction with data-index addon. Looks like this will require a deeper research.

**Comment by pefernan** [comment]
This has to be verified with the new addon, assigning to me meanwhile
